name: Create Release

on:
   push:
      tags:
         - 'v**'

   workflow_dispatch:

concurrency:
   cancel-in-progress: true
   group: "release"

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         -  name: Build
            run: |
               npm i
               npm run release

         -  name: Zip
            run: |
               pushd dist/weather-color-settings
               zip -r ../weather-color-settings.zip .
               popd

         -  name: Upload
            run: |
               gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --notes "${{ github.ref_name }}" dist/weather-color-settings.zip dist/weather-color-settings/module.json
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
